# Análisis de los datasets

In [46]:
import pandas as pd

In [47]:
files_path = [
    '../downloads/disney_plus_titles.csv',
    '../downloads/netflix_titles.csv'
]

In [48]:
dfs = []

for index, file_path in enumerate(files_path):
    if index == 0:
        df = pd.read_csv(file_path, sep=',')
        platform = 'DP'
    else:
        df = pd.read_csv(file_path, sep=';')
        platform = 'N'

    df['platform'] = platform

    dfs.append(df)

In [37]:
dfs_concat = pd.concat([df for df in dfs], ignore_index=True)

In [38]:
dfs_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10259 entries, 0 to 10258
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       10259 non-null  object
 1   type          10258 non-null  object
 2   title         10257 non-null  object
 3   director      7150 non-null   object
 4   cast          9243 non-null   object
 5   country       9207 non-null   object
 6   date_added    10244 non-null  object
 7   release_year  10257 non-null  object
 8   rating        10250 non-null  object
 9   duration      10254 non-null  object
 10  listed_in     10256 non-null  object
 11  description   10256 non-null  object
 12  platform      10259 non-null  object
dtypes: object(13)
memory usage: 1.0+ MB


In [9]:
dfs_concat.isnull().sum()

show_id            0
type               1
title              2
director        3109
cast            1016
country         1052
date_added        15
release_year       2
rating             9
duration           5
listed_in          3
description        3
platform           0
dtype: int64

Como se puede observar el dataset presenta valores faltantes en determinados campos. La mayor cantidad se encuentra en los campos de "director", "cast" y "country".

In [10]:
dfs_concat.sample(10)

show_id     type                                title        director  \
2781    s1332  TV Show  Five Came Back: The Reference Films             NaN   
4586    s3137    Movie                                 Game     Abhinay Deo   
1193    s1194    Movie                           Sister Act  Emile Ardolino   
3781    s2332  TV Show                            Home Game             NaN   
6198    s4749    Movie                          The Mansion      Tony Datis   
2490    s1041  TV Show                           Durarara!!             NaN   
10025   s8574    Movie                       Theo Who Lived  David Shisgall   
2129     s680  TV Show                        The Judgement             NaN   
5295    s3846  TV Show                          Cinta 100KG             NaN   
4711    s3262    Movie                          Suffragette    Sarah Gavron   

                                                    cast  \
2781                                                 NaN   
4586   Abhishek Bachchan, Kangana Ranaut, Anupam Kher...   
1193   Whoopi Goldberg, Maggie Smith, Harvey Keitel, ...   
3781                                                 NaN   
6198   Nathalie Odzierejko, Marc Jarousseau, Ludovik ...   
2490   Toshiyuki Toyonaga, Miyuki Sawashiro, Mamoru M...   
10025                                                NaN   
2129   Lapassalal Jiravechsoontornkul, Nontanun Anchu...   
5295   Sherry Alhadad, Sharifah Amani, Fezrul Khan, U...   
4711   Carey Mulligan, Helena Bonham Carter, Brendan ...   

                      country         date_added release_year rating  \
2781            United States   February 9, 2021         1945  TV-MA   
4586                    India  December 15, 2019         2011  TV-14   
1193            United States  November 12, 2019         1992     PG   
3781            United States      June 26, 2020         2020  TV-MA   
6198          France, Belgium      July 28, 2018         2017  TV-MA   
2490                    Japan     April 15, 2021         2016  TV-MA   
10025           United States  December 16, 2016         2016  TV-14   
2129                 Thailand      June 19, 2021         2018  TV-MA   
5295                      NaN        May 8, 2019         2016  TV-14   
4711   United Kingdom, France  November 16, 2019         2015  PG-13   

       duration                                          listed_in  \
2781   1 Season                                           TV Shows   
4586    135 min                    International Movies, Thrillers   
1193    101 min                              Comedy, Crime, Family   
3781   1 Season                                         Docuseries   
6198    100 min      Comedies, Horror Movies, International Movies   
2490   1 Season  Anime Series, Crime TV Shows, International TV...   
10025    86 min                                      Documentaries   
2129   1 Season  Crime TV Shows, International TV Shows, TV Dramas   
5295   1 Season  International TV Shows, Romantic TV Shows, TV ...   
4711    107 min                       Dramas, International Movies   

                                             description platform  
2781   This collection includes 12 World War II-era p...        N  
4586   A tycoon accuses three strangers of killing hi...        N  
1193   A low-rent lounge singer is forced to hide out...       DP  
3781   This docuseries profiles unique and dangerous ...        N  
6198   A group of students celebrates New Year's at a...        N  
2490   A young man looking for excitement moves to Ik...        N  
10025  American journalist Theo Padnos retraces the M...        N  
2129   After a traumatic incident at a party makes he...        N  
5295   Two female friends, each with confidence issue...        N  
4711   At the beginning of the 20th century, circumst...        N

## Columna "type"

In [11]:
dfs_concat['type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: type
Non-Null Count  Dtype 
--------------  ----- 
10258 non-null  object
dtypes: object(1)
memory usage: 80.3+ KB


In [13]:
dfs_concat['type'].isnull().sum()

1

Se puede ver que presenta un valor faltante

In [14]:
dfs_concat['type'].value_counts()

Movie            7183
TV Show          3074
William Wyler       1
Name: type, dtype: int64

Se puede ver que presenta un valor erróneo ya que, "William Wyler" probablemente sea un nombre de persona. Los valores posibles para esta columna son dos: "Movie" y "TV Show". 

Analizando los valores para el registro en cuestión:

In [15]:
dfs_concat[dfs_concat['type'] == 'William Wyler']

show_id           type title       director            cast  \
9871  Flying Fortress"  William Wyler   NaN  United States  March 31, 2017   

     country date_added release_year                         rating  \
9871    1944      TV-PG       40 min  Classic Movies, Documentaries   

                                               duration listed_in description  \
9871  This documentary centers on the crew of the B-...       NaN         NaN   

     platform  
9871        N

Se puede observar que los valores del registro están desviados y que los campos que presentan datos faltantes son los de "show_id" y "type", sin embargo, estos se pueden completar al analizar los registros antes y después para el caso del campo "show_id". 

In [16]:
dfs_concat.filter(items=[9870, 9871, 9872], axis=0)

show_id           type                            title  \
9870             s8420          Movie  The Memphis Belle: A Story of a   
9871  Flying Fortress"  William Wyler                              NaN   
9872             s8421          Movie       The Men Who Stare at Goats   

           director                                               cast  \
9870            NaN                                                NaN   
9871  United States                                     March 31, 2017   
9872   Grant Heslov  George Clooney, Ewan McGregor, Jeff Bridges, K...   

                            country    date_added release_year  \
9870                            NaN           NaN          NaN   
9871                           1944         TV-PG       40 min   
9872  United States, United Kingdom  June 4, 2019         2009   

                             rating  \
9870                            NaN   
9871  Classic Movies, Documentaries   
9872                              R   

                                               duration listed_in  \
9870                                                NaN       NaN   
9871  This documentary centers on the crew of the B-...       NaN   
9872                                             94 min  Comedies   

                                            description platform  
9870                                                NaN        N  
9871                                                NaN        N  
9872  A journalist latches onto an unbelievable stor...        N

Viendo que la columna "show_id" se saltea la numeración consecutiva, se tendría que generar nuevamente la numeración al finalizar la limpieza de datos en caso de que se utilice. En este caso, para la posterior modelación de los datos, esta columna no es relevante.

Para el campo "type", una posible solución sería hacer una búsqueda en internet por el nombre de la película para completar la información.

A su vez, se observa la presencia de una doble comilla al final del título. Este tipo de situaciones en donde se presentan caracteres adicionales en lugares donde no deberían estar, puede causar problemas por ejemplo, si se tiene que hacer alguna agrupación por columna. Se podrían utilizar expresiones regulares para filtrar los mismos.

## Columna "title"

In [17]:
dfs_concat['title'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: title
Non-Null Count  Dtype 
--------------  ----- 
10257 non-null  object
dtypes: object(1)
memory usage: 80.3+ KB


In [18]:
dfs_concat['title'].isnull().sum()

2

Se puede observar que presenta 2 valores nulos. Analizando dichos registros:

In [19]:
dfs_concat['title'].isnull()
dfs_concat[dfs_concat['title'].isnull() == True ]

show_id           type title       director  \
9652   and probably will."            NaN   NaN            NaN   
9871      Flying Fortress"  William Wyler   NaN  United States   

                cast country date_added release_year  \
9652             NaN     NaN        NaN          NaN   
9871  March 31, 2017    1944      TV-PG       40 min   

                             rating  \
9652                            NaN   
9871  Classic Movies, Documentaries   

                                               duration listed_in description  \
9652                                                NaN       NaN         NaN   
9871  This documentary centers on the crew of the B-...       NaN         NaN   

     platform  
9652        N  
9871        N

El segundo registro se analizó en el apartado anterior. 

In [20]:
dfs_concat.filter(items=[9651, 9652, 9653], axis=0)

show_id   type                    title  \
9651                 s8202  Movie  The Bad Education Movie   
9652   and probably will."    NaN                      NaN   
9653                 s8203  Movie             The Bad Kids   

                      director  \
9651            Elliot Hegarty   
9652                       NaN   
9653  Keith Fulton, Louis Pepe   

                                                   cast         country  \
9651  Jack Whitehall, Joanna Scanlan, Iain Glen, Eth...  United Kingdom   
9652                                                NaN             NaN   
9653                                                NaN   United States   

             date_added release_year rating duration      listed_in  \
9651  December 15, 2018         2015  TV-MA   87 min       Comedies   
9652                NaN          NaN    NaN      NaN            NaN   
9653      April 1, 2017         2016  TV-MA  101 min  Documentaries   

                                            description platform  
9651  Britain's most ineffective but caring teacher ...        N  
9652                                                NaN        N  
9653  In this documentary, teachers at a Mojave Dese...        N

Mientras que al ver el registro correspondiente a la posición 9652, este se puede eliminar ya que no es posible determinar los datos correspondientes a los campos con valores nulos, en base a la poca información que presenta.

Se podría ver si se repite algún título

In [21]:
dfs_concat['title'].value_counts().sort_values(ascending=False)

For the Birds         2
Chicken Little        2
Bedtime Stories       2
Liv and Maddie        2
Genius                2
                     ..
Zenda                 1
Zindagi Gulzar Hai    1
Zinzana               1
Zodiac                1
Zubaan                1
Name: title, Length: 10214, dtype: int64

Se presenta la repetición de títulos. Para estos casos, es conveniente convertir a minúsculas, eliminar espacios y caracteres especiales, para poder obtener todos los títulos que se repiten. Observando algunos de estos títulos:

In [22]:
dfs_concat[dfs_concat['title'].isin(['For the Birds', 'Chicken Little', 'Liv and Maddie'])]

show_id     type           title         director  \
242     s243  TV Show  Liv and Maddie              NaN   
789     s790    Movie  Chicken Little      Mark Dindal   
896     s897    Movie   For the Birds  Ralph Eggleston   
7916   s6467    Movie  Chicken Little      Mark Dindal   
8230   s6781    Movie   For the Birds    Richard Miron   
8771   s7322  TV Show  Liv and Maddie              NaN   

                                                   cast        country  \
242   Dove Cameron, Joey Bragg, Tenzing Norgay Train...  United States   
789   Zach Braff, Garry Marshall, Don Knotts, Patric...  United States   
896                                                 NaN  United States   
7916  Zach Braff, Joan Cusack, Patrick Stewart, Stev...  United States   
8230                                       Kathy Murphy  United States   
8771  Dove Cameron, Joey Bragg, Tenzing Norgay Train...  United States   

             date_added release_year rating   duration  \
242      April 23, 2021         2013   TV-G  4 Seasons   
789   November 12, 2019         2005      G     84 min   
896   November 12, 2019         2001      G      4 min   
7916     March 16, 2016         2005      G     82 min   
8230  September 1, 2019         2018  TV-MA     93 min   
8771     April 23, 2017         2017   TV-G  4 Seasons   

                               listed_in  \
242          Comedy, Coming of Age, Kids   
789          Animation, Comedy, Disaster   
896            Animation, Comedy, Family   
7916  Children & Family Movies, Comedies   
8230                       Documentaries   
8771               Kids' TV, TV Comedies   

                                            description platform  
242   The series follows 15-year-old twins Liv and M...       DP  
789   When disaster strikes, Chicken Little hatches ...       DP  
896   Small birds mock a big bird who tries to sit w...       DP  
7916  No one believes Chicken Little when he tries t...        N  
8230  A woman with a passion for fowl keeps a menage...        N  
8771  After four years in Hollywood as a television ...        N

- "For the Birds": se trata de dos películas distintas, con el mismo nombre.
- "Chicken Little": es la misma película que se subió a ambas plataformas.
- "Liv and Maddie": es la temporada 4 de un programa de televisión (parece ser el mismo) pero varían los años de estreno.

# Columna "date_added"

In [23]:
dfs_concat['date_added'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: date_added
Non-Null Count  Dtype 
--------------  ----- 
10244 non-null  object
dtypes: object(1)
memory usage: 80.3+ KB


In [24]:
dfs_concat['date_added'].isnull().sum()

15

Se observa el registro con los campos nulos:

In [25]:
dfs_concat[dfs_concat['date_added'].isnull() == True]

show_id     type  \
1439                 s1440  TV Show   
1440                 s1441  TV Show   
1441                 s1442  TV Show   
7516                 s6067  TV Show   
7624                 s6175  TV Show   
8245                 s6796  TV Show   
8256                 s6807  TV Show   
8351                 s6902  TV Show   
8646                 s7197  TV Show   
8704                 s7255  TV Show   
8856                 s7407  TV Show   
9297                 s7848  TV Show   
9632                 s8183  TV Show   
9652   and probably will."      NaN   
9870                 s8420    Movie   

                                            title director  \
1439                         Disney Kirby Buckets      NaN   
1440                               Disney Mech-X4      NaN   
1441                           Imagination Movers      NaN   
7516  A Young Doctor's Notebook and Other Stories      NaN   
7624              Anthony Bourdain: Parts Unknown      NaN   
8245                                      Frasier      NaN   
8256                                      Friends      NaN   
8351                              Gunslinger Girl      NaN   
8646                                     Kikoriki      NaN   
8704                          La Familia P. Luche      NaN   
8856                                        Maron      NaN   
9297                                 Red vs. Blue      NaN   
9632                 The Adventures of Figaro Pho      NaN   
9652                                          NaN      NaN   
9870              The Memphis Belle: A Story of a      NaN   

                                                   cast         country  \
1439  Jacob Bertrand, Mekai Curtis, Cade Sutton, Oli...   United States   
1440  Nathaniel Potvin, Raymond Cham, Kamran Lucas, ...          Canada   
1441  Rich Collins, Dave Poche, Scott Durbin, Scott ...   United States   
7516  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...  United Kingdom   
7624                                   Anthony Bourdain   United States   
8245  Kelsey Grammer, Jane Leeves, David Hyde Pierce...   United States   
8256  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...   United States   
8351  Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...           Japan   
8646                                      Igor Dmitriev             NaN   
8704  Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...   United States   
8856  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...   United States   
9297  Burnie Burns, Jason Saldaña, Gustavo Sorola, G...   United States   
9632  Luke Jurevicius, Craig Behenna, Charlotte Haml...       Australia   
9652                                                NaN             NaN   
9870                                                NaN             NaN   

     date_added release_year rating    duration  \
1439        NaN         2014  TV-Y7   3 Seasons   
1440        NaN         2016  TV-Y7   2 Seasons   
1441        NaN         2008   TV-Y   3 Seasons   
7516        NaN         2013  TV-MA   2 Seasons   
7624        NaN         2018  TV-PG   5 Seasons   
8245        NaN         2003  TV-PG  11 Seasons   
8256        NaN         2003  TV-14  10 Seasons   
8351        NaN         2008  TV-14   2 Seasons   
8646        NaN         2010   TV-Y   2 Seasons   
8704        NaN         2012  TV-14   3 Seasons   
8856        NaN         2016  TV-MA   4 Seasons   
9297        NaN         2015     NR  13 Seasons   
9632        NaN         2015  TV-Y7   2 Seasons   
9652        NaN          NaN    NaN         NaN   
9870        NaN          NaN    NaN         NaN   

                                              listed_in  \
1439            Action-Adventure, Comedy, Coming of Age   
1440          Action-Adventure, Comedy, Science Fiction   
1441                                        Kids, Music   
7516           British TV Shows, TV Comedies, TV Dramas   
7624                                         Docuseries   
8245                     Clas

Por otro lado, este campo no es del tipo fecha por lo que es conveniente convertirlo para su posterior utilización. Tener cuidado:

In [27]:
dfs_concat[dfs_concat['release_year'] == '40 min']

show_id           type title       director            cast  \
9871  Flying Fortress"  William Wyler   NaN  United States  March 31, 2017   

     country date_added release_year                         rating  \
9871    1944      TV-PG       40 min  Classic Movies, Documentaries   

                                               duration listed_in description  \
9871  This documentary centers on the crew of the B-...       NaN         NaN   

     platform  
9871        N

Se tiene que resolver primero el problema de los datos corridos en algunos registros, para luego poder hacer dicha conversión de los datos de la columna a fecha, teniendo cuidado también de que no haya caracteres especiales presentes en esta columna. En caso de haberlos, se podrían filtrar utilizando expresiones regulares.

# Columna "release_year"

In [28]:
dfs_concat['release_year'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: release_year
Non-Null Count  Dtype 
--------------  ----- 
10257 non-null  object
dtypes: object(1)
memory usage: 80.3+ KB


In [29]:
dfs_concat['release_year'].isnull().sum()

2

Se observan los dos valores faltantes:

In [30]:
dfs_concat[dfs_concat['release_year'].isnull() == True]

show_id   type                            title director  \
9652   and probably will."    NaN                              NaN      NaN   
9870                 s8420  Movie  The Memphis Belle: A Story of a      NaN   

     cast country date_added release_year rating duration listed_in  \
9652  NaN     NaN        NaN          NaN    NaN      NaN       NaN   
9870  NaN     NaN        NaN          NaN    NaN      NaN       NaN   

     description platform  
9652         NaN        N  
9870         NaN        N

El primer registro ya se analizó, mientras que el segundo registro al tener el título de la película, se podrían completar los datos faltantes buscando la información correspondiente.

Por otra parte, los valores de esta columna no son del tipo numéricos. Es conveniente convertirlos. Pero se tiene el siguiente problema (que se vio en el apartado anterior):

In [202]:
dfs_concat['release_year'].value_counts().sample(10)

40 min      1
1993       28
2018       65
2016      902
1967        5
1973        2
2008      136
2004       64
1985       10
1959        5
Name: release_year, dtype: int64

In [203]:
dfs_concat[dfs_concat['release_year'] == '40 min']

show_id           type title       director            cast  \
9871  Flying Fortress"  William Wyler   NaN  United States  March 31, 2017   

     country date_added release_year                         rating  \
9871    1944      TV-PG       40 min  Classic Movies, Documentaries   

                                               duration listed_in description  \
9871  This documentary centers on the crew of the B-...       NaN         NaN   

     platform  
9871        N

Se puede observar que presenta la palabra "min", esto es debido a que se vio que habían datos corridos en los registros y primero tiene que solucionarse eso. 

# Columna "duration"

In [204]:
dfs_concat['duration'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: duration
Non-Null Count  Dtype 
--------------  ----- 
10254 non-null  object
dtypes: object(1)
memory usage: 80.3+ KB


In [205]:
dfs_concat['duration'].isnull().sum()

5

In [206]:
dfs_concat[dfs_concat['duration'].isnull() == True]

show_id   type                                 title  \
6991                 s5542  Movie                       Louis C.K. 2017   
7244                 s5795  Movie                 Louis C.K.: Hilarious   
7263                 s5814  Movie  Louis C.K.: Live at the Comedy Store   
9652   and probably will."    NaN                                   NaN   
9870                 s8420  Movie       The Memphis Belle: A Story of a   

        director        cast        country          date_added release_year  \
6991  Louis C.K.  Louis C.K.  United States       April 4, 2017         2017   
7244  Louis C.K.  Louis C.K.  United States  September 16, 2016         2010   
7263  Louis C.K.  Louis C.K.  United States     August 15, 2016         2015   
9652         NaN         NaN            NaN                 NaN          NaN   
9870         NaN         NaN            NaN                 NaN          NaN   

      rating duration listed_in  \
6991  74 min      NaN    Movies   
7244  84 min      NaN    Movies   
7263  66 min      NaN    Movies   
9652     NaN      NaN       NaN   
9870     NaN      NaN       NaN   

                                            description platform  
6991  Louis C.K. muses on religion, eternal love, gi...        N  
7244  Emmy-winning comedy writer Louis C.K. brings h...        N  
7263  The comic puts his trademark hilarious/thought...        N  
9652                                                NaN        N  
9870                                                NaN        N

El registro 9652 ya se trató (tiene que eliminarse). Para el registro 9870 podría obtenerse la información faltante a través del título de la película. Mientras que para la columna "rating" de los restantes registros, se puede ver que sus valores son erróneos y que corresponden a la columna "duration", por lo tanto tiene que resolverse antes esta desviación de datos en ambas columnas.

In [207]:
dfs_concat['duration'].value_counts()

1 Season      2012
2 Seasons      507
3 Seasons      244
90 min         179
94 min         174
              ... 
237 min          1
17 Seasons       1
253 min          1
208 min          1
191 min          1
Name: duration, Length: 231, dtype: int64

Se puede ver que el tipo de dato no es numérico, por lo que será necesario convertir la columna para poder trabajar con los datos. A tener en cuenta:

In [269]:
dfs_concat[dfs_concat['release_year'] == '40 min']

show_id           type title       director            cast  \
8421  Flying Fortress"  William Wyler   NaN  United States  March 31, 2017   

     country date_added release_year                         rating  \
8421    1944      TV-PG       40 min  Classic Movies, Documentaries   

                                               duration listed_in description  \
8421  This documentary centers on the crew of the B-...       NaN         NaN   

     platform  
8421        N

Como se analizó anteriormente, hay registros que presentan datos corridos. Por lo tanto, primero se tiene que solucionar esto, para luego, mediante el uso de expresiones regulares quitar la palabras "min", "Season" y "Seasons" y, castear los datos a un valor entero. Debido a esto, al realizar la transformación anterior, hay que recordar que: cuando se tiene una película, el dato es la duración en minutos y, cuando se tiene un programa de televisión, el valor es la cantidad de temporadas.

## Columna "cast"

In [208]:
dfs_concat['cast'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10259 entries, 0 to 10258
Series name: cast
Non-Null Count  Dtype 
--------------  ----- 
9243 non-null   object
dtypes: object(1)
memory usage: 80.3+ KB


In [209]:
dfs_concat['cast'].isnull().sum()

1016

Se puede observar que faltan datos y esta columna es muy importante para el modelado de datos posterior. 

In [210]:
dfs_concat[dfs_concat['cast'].isnull() == True]

show_id     type                                     title  \
11        s12    Movie                        Puppy for Hanukkah   
15        s16    Movie                                   Baymax!   
26        s27    Movie  Marvel Studios’ 2021 Disney+ Day Special   
27        s28    Movie                            Obi-Wan Kenobi   
35        s36    Movie                      The Little Matchgirl   
...       ...      ...                                       ...   
10198   s8747    Movie                                    Winnie   
10207   s8756  TV Show                         Women Behind Bars   
10208   s8757    Movie                                 Woodstock   
10215   s8764    Movie           WWII: Report from the Aleutians   
10255   s8804  TV Show                               Zombie Dumb   

             director cast                                     country  \
11                NaN  NaN                                         NaN   
15                NaN  NaN                                         NaN   
26                NaN  NaN                                         NaN   
27                NaN  NaN                                         NaN   
35       Roger Allers  NaN                               United States   
...               ...  ...                                         ...   
10198  Pascale Lamche  NaN  France, Netherlands, South Africa, Finland   
10207             NaN  NaN                               United States   
10208   Barak Goodman  NaN                               United States   
10215     John Huston  NaN                               United States   
10255             NaN  NaN                                         NaN   

              date_added release_year rating   duration  \
11     November 19, 2021         2020   TV-G      4 min   
15     November 12, 2021         2021   TV-G      1 min   
26     November 12, 2021         2021  TV-PG     14 min   
27     November 12, 2021         2021  TV-PG      1 min   
35     November 12, 2021         2006      G      7 min   
...                  ...          ...    ...        ...   
10198  February 26, 2018         2017  TV-14     85 min   
10207   November 1, 2016         2010  TV-14  3 Seasons   
10208    August 13, 2019         2019  TV-MA     97 min   
10215     March 31, 2017         1943  TV-PG     45 min   
10255       July 1, 2019         2018  TV-Y7  2 Seasons   

                                    listed_in  \
11                      Comedy, Family, Music   
15                                  Animation   
26                                     Movies   
27          Action-Adventure, Science Fiction   
35                           Animation, Drama   
...                                       ...   
10198     Documentaries, International Movies   
10207              Crime TV Shows, Docuseries   
10208         Documentaries, Music & Musicals   
10215                           Documentaries   
10255  Kids' TV, Korean TV Shows, TV Comedies   

                                             description platform  
11     Check out Daveed Digg's official music video "...       DP  
15           “Baymax!” premieres on Disney+ summer 2022.       DP  
26     Marvel Studios’ Disney+ Day Special explores t...       DP  
27     A behind the scenes look of the "Obi-Wan Kenob...       DP  
35     A poor matchgirl sees happy images in the flam...       DP  
...                                                  ...      ...  
10198  Winnie Mandela speaks about her extraordinary ...        N  
10207  This reality series recounts true stories of w...        N  
10208  For the 50th anniversary of the legendary Wood...        N  
10215  Filmmaker John Huston narrates this Oscar-nomi...        N  
10255  While living alone in a spooky town, a young g...        N  

[1016 rows x 13 columns]

Hay que recordar que primero se deben solucionar los corrimientos presentes en algunos registros que también afectan a esta columna. Observando rápidamente se podrían completar ciertos valores faltantes teniendo en cuenta la columna "title", pero sería un trabajo manual. 

Para analizar esta columna, al tratarse de una cadena de caracteres, se la trabajará un poco (Recordar: a la columna se la trabajará sin haber solucionado el incoveniente de los corrimientos, solo para profundizar un poco más el análisis y que quede registrado qué pasos deberían seguirse):

In [211]:
dfs_concat['cast'] = (dfs_concat.cast.str.split(','))
dfs_concat = dfs_concat.explode('cast')

In [212]:
dfs_concat.head(10)

show_id   type                                             title  \
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
0      s1  Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1      s2  Movie                            Ernest Saves Christmas   
1      s2  Movie                            Ernest Saves Christmas   
1      s2  Movie                            Ernest Saves Christmas   
2      s3  Movie                      Ice Age: A Mammoth Christmas   

                            director                   cast        country  \
0  Alonso Ramirez Ramos, Dave Wasson   Chris Diamantopoulos            NaN   
0  Alonso Ramirez Ramos, Dave Wasson           Tony Anselmo            NaN   
0  Alonso Ramirez Ramos, Dave Wasson        Tress MacNeille            NaN   
0  Alonso Ramirez Ramos, Dave Wasson            Bill Farmer            NaN   
0  Alonso Ramirez Ramos, Dave Wasson           Russi Taylor            NaN   
0  Alonso Ramirez Ramos, Dave Wasson           Corey Burton            NaN   
1                        John Cherry             Jim Varney            NaN   
1                        John Cherry          Noelle Parker            NaN   
1                        John Cherry          Douglas Seale            NaN   
2                       Karen Disher  Raymond Albert Romano  United States   

          date_added release_year rating duration                  listed_in  \
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
0  November 26, 2021         2016   TV-G   23 min          Animation, Family   
1  November 26, 2021         1988     PG   91 min                     Comedy   
1  November 26, 2021         1988     PG   91 min                     Comedy   
1  November 26, 2021         1988     PG   91 min                     Comedy   
2  November 26, 2021         2011   TV-G   23 min  Animation, Comedy, Family   

                                         description platform  
0   Join Mickey and the gang as they duck the halls!       DP  
0   Join Mickey and the gang as they duck the halls!       DP  
0   Join Mickey and the gang as they duck the halls!       DP  
0   Join Mickey and the gang as they duck the halls!       DP  
0   Join Mickey and the gang as they duck the halls!       DP  
0   Join Mickey and the gang as they duck the halls!       DP  
1  Santa Claus passes his magic bag to a new St. ...       DP  
1  Santa Claus passes his magic bag to a new St. ...       DP  
1  Santa Claus passes his magic bag to a new St. ...       DP  
2          Sid the Sloth is on Santa's naughty list.       DP

Como se observa, se separó cada actor por fila.

Se determina si hay datos que se repiten:

In [214]:
dfs_concat['cast'].value_counts()

 Anupam Kher              40
 Jim Cummings             33
 Rupa Bhimani             31
 Takahiro Sakurai         30
 Julie Tejwani            28
                          ..
Jessica Sula               1
 Mark Cassius              1
 Colin Paradine            1
 Terri Oliver              1
 Chittaranjan Tripathy     1
Name: cast, Length: 41707, dtype: int64

Como se puede observar, hay datos que se repiten. Lo conveniente sería convertir los datos a minúsculas, quitar espacios y caracteres especiales, para obtener la cantidad de veces que se repite cada actor.

# Idiomas

Con el análisis previo se vio que la columna "title" tiene presente más de un idioma. Por ejemplo: se vio para la película "Esperando la carroza", varios títulos son en inglés como así se encontró también un título en coreano.

In [218]:
dfs_concat[dfs_concat['title'] == '최강전사 미니특공대 : 영웅의 탄생']

show_id   type                title       director             cast  \
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee     Um Sang-hyun   
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee   Yang Jeong-hwa   
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee    Jeon Tae-yeol   
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee    Shin Yong-woo   
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee     Lee So-young   
8558   s7109  Movie  최강전사 미니특공대 : 영웅의 탄생  Young Jun Lee          So-yeon   

     country         date_added release_year rating duration  \
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   
8558     NaN  September 1, 2018         2018  TV-Y7   68 min   

                     listed_in  \
8558  Children & Family Movies   
8558  Children & Family Movies   
8558  Children & Family Movies   
8558  Children & Family Movies   
8558  Children & Family Movies   
8558  Children & Family Movies   

                                            description platform  
8558  Miniforce, a special task force of elite range...        N  
8558  Miniforce, a special task force of elite range...        N  
8558  Miniforce, a special task force of elite range...        N  
8558  Miniforce, a special task force of elite range...        N  
8558  Miniforce, a special task force of elite range...        N  
8558  Miniforce, a special task force of elite range...        N

# Conclusión

La columna "title" presenta al menos tres idiomas.

Transformaciones para aplicar al dataset:
- Solucionar los desviamientos de datos en determinados registros, ya sea un desviamiento completo que afecta a todas las columnas como así también los desviamientos parciales, como se vio por ejemplo, que afectaban a dos columnas en donde la información estaba intercambiada.
- Determinar si se puede completar datos faltantes en columnas a partir de la información presente en otra/s columna/s. De no ser así, y no contar con información suficiente, eliminar el registro ya que, no aporta información útil.
- En columnas como "title" y "description" convertir a minúsculas y quitar espacios y caracteres especiales.
- En la columna "cast", separar cada actor teniendo en cuenta como separador la coma para después mediante la función explode() de Pandas poder separarlos por fila. Convertir a minúsculas y, quitar espacios y caracteres especiales.
- La columna "date_added" tiene que convertirse a un formato del tipo fecha para poder utilizarla.
- Las columnas "release_year" y "duration" tienen que convertirse a un formato numérico, teniendo en cuenta que a los valores correspondientes a la columna "duration" hay que eliminar antes de la conversión, las palabras "min", "Season" y "Seasons" (recordando que el valor final corresponde a la duración en minutos si se trata de una película o a la cantidad de temporadas si es un programa de televisión).
- Eliminar registros duplicados.